apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: customerfreezewindows.upgrade.managed.openshift.io
spec:
  group: upgrade.managed.openshift.io
  names:
    kind: CustomerFreezeWindow
    listKind: CustomerFreezeWindowList
    plural: customerfreezewindows
    singular: customerfreezewindow
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CustomerFreezeWindow is the Schema for the customerfreezewindows
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CustomerFreezeWindowSpec defines the desired state of CustomerFreezeWindow
          properties:
            fromUtc:
              properties:
                dayOfMonth:
                  maximum: 31
                  minimum: 1
                  type: integer
                dayOfWeek:
                  enum:
                  - Monday
                  - Tuesday
                  - Wednesday
                  - Thursday
                  - Friday
                  - Saturday
                  - Sunday
                  type: string
                month:
                  enum:
                  - January
                  - February
                  - March
                  - April
                  - May
                  - June
                  - July
                  - August
                  - September
                  - October
                  - November
                  - December
                  type: string
                time:
                  description: Time in UTC like "01:00"
                  format: ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$
                  type: string
                timestamp:
                  format: date-time
                  type: string
                weekOfMonth:
                  maximum: 4
                  minimum: 1
                  type: integer
              required:
              - month
              - time
              type: object
            toUtc:
              properties:
                dayOfMonth:
                  maximum: 31
                  minimum: 1
                  type: integer
                dayOfWeek:
                  enum:
                  - Monday
                  - Tuesday
                  - Wednesday
                  - Thursday
                  - Friday
                  - Saturday
                  - Sunday
                  type: string
                month:
                  enum:
                  - January
                  - February
                  - March
                  - April
                  - May
                  - June
                  - July
                  - August
                  - September
                  - October
                  - November
                  - December
                  type: string
                time:
                  description: Time in UTC like "01:00"
                  format: ^([0-1][0-9]|[2][0-3]):([0-5][0-9])$
                  type: string
                timestamp:
                  format: date-time
                  type: string
                weekOfMonth:
                  maximum: 4
                  minimum: 1
                  type: integer
              required:
              - month
              - time
              type: object
          required:
          - fromUtc
          - toUtc
          type: object
        status:
          description: CustomerFreezeWindowStatus defines the observed state of CustomerFreezeWindow
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
