apiVersion: v1
kind: ConfigMap
metadata:
  name: managed-upgrade-operator-config
data:
  config.yaml: |
    maintenance:
      controlPlaneTime: 90
      workerNodeTime: 8
      ignoredAlerts:
        controlPlaneCriticals:
        - etcdMembersDown
        - KubeDeploymentReplicasMismatch
        - ClusterOperatorDown
    scale:
      timeOut: 30
    upgradeWindow:
      timeOut: 60
    nodeDrain:
      timeOut: 45